[project]
name = "invemp"
version = "1.1.0"
description = "The basic inventory management app built with Flask."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"